// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace PetGroomer.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entities.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("AppointmentId");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<Guid>("PetId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f184f942-063e-48a7-aa63-d926cbf3500f"),
                            DateTime = new DateTime(2022, 1, 3, 20, 46, 20, 975, DateTimeKind.Local).AddTicks(6760),
                            Details = "short cut and shampoo",
                            Duration = 30,
                            PetId = new Guid("db5ca57b-3979-40f2-9999-6afae0304bec")
                        },
                        new
                        {
                            Id = new Guid("70c451a9-d7e0-4aa5-bf19-40ea1d86250c"),
                            DateTime = new DateTime(2022, 1, 3, 20, 46, 20, 975, DateTimeKind.Local).AddTicks(6800),
                            Details = "matted and lice",
                            Duration = 45,
                            PetId = new Guid("43acbff7-92d5-47e7-94db-89195c296e3f")
                        });
                });

            modelBuilder.Entity("Entities.Models.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("OwnerId");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f17c14d9-425b-46c6-86b4-2d8478f16fd2"),
                            Email = "kyle@email.com",
                            FirstName = "Kyle",
                            LastName = "Skinner",
                            Phone = "7203832311"
                        },
                        new
                        {
                            Id = new Guid("4f0528d3-5f4b-4333-9801-d31ae2888d88"),
                            Email = "kathleen@email.com",
                            FirstName = "Kathleen",
                            LastName = "Skinner",
                            Phone = "7032826710"
                        });
                });

            modelBuilder.Entity("Entities.Models.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("PetId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PetTypeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PetTypeId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db5ca57b-3979-40f2-9999-6afae0304bec"),
                            Name = "Fozzie",
                            Notes = "Energetic pet",
                            OwnerId = new Guid("f17c14d9-425b-46c6-86b4-2d8478f16fd2"),
                            PetTypeId = new Guid("c70bb081-cf3b-4e35-ae44-abb10c4c582a")
                        },
                        new
                        {
                            Id = new Guid("8ce9498f-c7ba-49a7-8236-6aa43dc97250"),
                            Name = "Rosie",
                            Notes = "annoying",
                            OwnerId = new Guid("f17c14d9-425b-46c6-86b4-2d8478f16fd2"),
                            PetTypeId = new Guid("c70bb081-cf3b-4e35-ae44-abb10c4c582a")
                        },
                        new
                        {
                            Id = new Guid("43acbff7-92d5-47e7-94db-89195c296e3f"),
                            Name = "Stormy",
                            Notes = "ugliest dog",
                            OwnerId = new Guid("4f0528d3-5f4b-4333-9801-d31ae2888d88"),
                            PetTypeId = new Guid("c70bb081-cf3b-4e35-ae44-abb10c4c582a")
                        });
                });

            modelBuilder.Entity("Entities.Models.PetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("PetTypeId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PetTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c70bb081-cf3b-4e35-ae44-abb10c4c582a"),
                            Type = "Dog"
                        },
                        new
                        {
                            Id = new Guid("ca738c4a-3538-48f4-b7ce-04f8e2ee45f6"),
                            Type = "Cat"
                        });
                });

            modelBuilder.Entity("Entities.Models.Pet", b =>
                {
                    b.HasOne("Entities.Models.Owner", null)
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.PetType", "PetType")
                        .WithMany()
                        .HasForeignKey("PetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PetType");
                });

            modelBuilder.Entity("Entities.Models.Owner", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
